### ISSUE TITLE
Redstonesignal on tubes

### ISSUE THREAD

**Issue by TimGoll** [elytra/Teckle#36] opened 2018-09-13 07:47 UTC
#### Feature description.
![image](https://user-images.githubusercontent.com/13639408/45474405-008c9700-b73a-11e8-83ac-12c269011902.png)
Like in RP you should be able to transport a redstone signal over the tubes

#### Does this feature involve mod compatability, if so, which mods
No other mods needed

**Comment by adrwa** [comment] 2018-09-13 11:33
Duplicate of #32

**Closed as completed by adrwa** 2018-09-13 11:33 UTC
Labels: s: Duplicate

**Comment by TimGoll** [comment] 2018-09-13 11:36
my bad, sorry!
